USE bank_db;

START TRANSACTION;
UPDATE Account SET balance = balance - 1000 WHERE account_no = 10001;
SAVEPOINT s1;
UPDATE Account SET balance = balance + 1000 WHERE account_no = 10002;
ROLLBACK TO SAVEPOINT s1;    
COMMIT;                      


START TRANSACTION;
DELETE FROM Loan_Payment WHERE loan_id = 9000;
SELECT COUNT(*) FROM Loan_Payment WHERE loan_id = 9000;   
ROLLBACK;
SELECT COUNT(*) FROM Loan_Payment WHERE loan_id = 9000;  
SELECT @@transaction_isolation;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;


CALL transfer(10003, 10004, 5000);        
CALL transfer(10004, 10003, 99999999);      
SELECT account_no, balance FROM Account;
